### ISSUE TITLE
Release 3.0.1 not on nuget.org

### ISSUE THREAD

**Issue by mohlerm** [Particular/NServiceBus.Metrics.ServiceControl.Msmq#22]
Hi

Is there a reason why 3.0.1 has not been released to nuget.org?
We are waiting on this package since #12 is stopping us upgrading NServiceBus.Metrics.ServiceControl to 3.0.2.

Thank you very much.

Best

**Comment by SzymonPobiega** [comment]
Good catch! Thanks!

@Particular/nservicebus-maintainers can you take a look at this?

**Comment by mikeminutillo** [comment]
@mohlerm sorry for missing this. The release has been pushed to NuGet now.
